In [ ]:
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
import numpy as np

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

x_train = x_train.reshape(x_train.shape[0], -1) / 255.0
x_test = x_test.reshape(x_test.shape[0], -1) / 255.0
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# 1
model = Sequential()
model.add(Dense(10, input_dim=784, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10, validation_split=0.1)

_, test_acc = model.evaluate(x_test, y_test)
print(f"Точность - {test_acc*100}%")

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.6533 - loss: 1.0049 - val_accuracy: 0.8212 - val_loss: 0.5022
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8333 - loss: 0.4839 - val_accuracy: 0.8425 - val_loss: 0.4476
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8474 - loss: 0.4417 - val_accuracy: 0.8470 - val_loss: 0.4347
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8550 - loss: 0.4162 - val_accuracy: 0.8452 - val_loss: 0.4455
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8576 - loss: 0.4126 - val_accuracy: 0.8495 - val_loss: 0.4258
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.8601 - loss: 0.4008 - val_accuracy: 0.8465 - val_loss: 0.4244
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8619 - loss: 0.3933 - val_accuracy: 0.8508 - val_loss: 0.4123
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8592 - loss: 0.3960 -

In [ ]:
model2 = Sequential()
model2.add(Dense( 50, input_dim=784, activation='relu'))
model2.add(Dense(10, activation='softmax'))
model2.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])
model2.fit(x_train, y_train, epochs=10, validation_split=0.1)

_, test_acc2 = model2.evaluate(x_test, y_test)
print(f"Точность - {test_acc2*100}%")

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.7596 - loss: 0.7077 - val_accuracy: 0.8418 - val_loss: 0.4398
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8547 - loss: 0.4123 - val_accuracy: 0.8585 - val_loss: 0.3930
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8691 - loss: 0.3655 - val_accuracy: 0.8633 - val_loss: 0.3879
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8759 - loss: 0.3428 - val_accuracy: 0.8673 - val_loss: 0.3614
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.8804 - loss: 0.3295 - val_accuracy: 0.8720 - val_loss: 0.3607
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8871 - loss: 0.3092 - val_accuracy: 0.8780 - val_loss: 0.3425
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8892 - loss: 0.2964 - val_accuracy: 0.8777 - val_loss: 0.3399
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8943 - loss: 0.2920 -

In [ ]:
model3 = Sequential()
model3.add(Dense(50, input_dim=784, activation='relu'))
model3.add(Dense(50, activation='relu'))
model3.add(Dense(10, activation='softmax'))
model3.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])
model3.fit(x_train, y_train, epochs=10, validation_split=0.1)

_, test_acc3 = model3.evaluate(x_test, y_test)
print(f"Точность - {test_acc3*100}%")

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.7505 - loss: 0.7051 - val_accuracy: 0.8483 - val_loss: 0.4193
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8565 - loss: 0.4010 - val_accuracy: 0.8550 - val_loss: 0.3964
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - accuracy: 0.8672 - loss: 0.3651 - val_accuracy: 0.8647 - val_loss: 0.3764
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.8776 - loss: 0.3368 - val_accuracy: 0.8712 - val_loss: 0.3716
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.8876 - loss: 0.3084 - val_accuracy: 0.8783 - val_loss: 0.3354
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - accuracy: 0.8910 - loss: 0.3013 - val_accuracy: 0.8647 - val_loss: 0.3924
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8926 - loss: 0.2910 - val_accuracy: 0.8772 - val_loss: 0.3598
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8960 - loss: 0.277

In [ ]:
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten
import numpy as np
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train[:,:,:,np.newaxis] / 255.0
x_test = x_test[:,:,:,np.newaxis] / 255.0
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

model4 = Sequential()
model4.add(Conv2D(filters=64, kernel_size=2, padding='same',
activation='relu', input_shape=(28,28, 1)))
model4.add(MaxPooling2D(pool_size=2))
model4.add(Flatten())
model4.add(Dense(10, activation='softmax'))
model4.compile(loss='categorical_crossentropy', optimizer='adam',
metrics=['accuracy'])
model4.fit(x_train, y_train, epochs=10, validation_split=0.1)

_, test_acc4 = model4.evaluate(x_test, y_test)
print(f"Точность - {test_acc4*100}%")


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 45s 26ms/step - accuracy: 0.7987 - loss: 0.5754 - val_accuracy: 0.8757 - val_loss: 0.3383
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 43s 25ms/step - accuracy: 0.8862 - loss: 0.3250 - val_accuracy: 0.8965 - val_loss: 0.2989
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 43s 25ms/step - accuracy: 0.9030 - loss: 0.2776 - val_accuracy: 0.8770 - val_loss: 0.3339
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 43s 25ms/step - accuracy: 0.9093 - loss: 0.2520 - val_accuracy: 0.8892 - val_loss: 0.3030
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 81s 25ms/step - accuracy: 0.9134 - loss: 0.2445 - val_accuracy: 0.9008 - val_loss: 0.2756
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 81s 24ms/step - accuracy: 0.9179 - loss: 0.2280 - val_accuracy: 0.9020 - val_loss: 0.2785
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 82s 25ms/step - accuracy: 0.9240 - loss: 0.2138 - val_accuracy: 0.9038 - val_loss: 0.2744
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 82s 25ms/step - accuracy: 0.9260 -

In [24]:
import numpy as np

# Функция активации (логистический сигмоид)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Производная сигмоида
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Параметры
X = np.array([0.4, -0.4]) # Входной вектор

# Инициализация весов в диапазоне [-0.3, 0.3]
W1 = np.random.uniform(-0.3, 0.3, (2, 3))  # Матрица весов для 1 слоя (2 входа -> 3 нейрона)
W2 = np.random.uniform(-0.3, 0.3, (3, 3))  # Матрица весов для 2 слоя (3 нейрона -> 3 выхода)

Y = np.array([0.3, 0.5, 0.8]) # Эталонный выход

learning_rate = 0.25 # Скорость обучения

# Прямое распространение
net_h = np.dot(X, W1)   # Считаем net на скрытом слое
out_h = sigmoid(net_h)  # Выход скрытого слоя после активации

net_o = np.dot(out_h, W2)  # Считаем net на выходном слое
out_o = sigmoid(net_o)     # Выход выходного слоя после активации

# Вычисление ошибки
error = Y - out_o

# Обратное распространение ошибки
delta_o = error * sigmoid_derivative(net_o)          # Ошибка на выходном слое
delta_h = np.dot(delta_o, W2.T) * sigmoid_derivative(net_h) # Ошибка на скрытом слое

# Обновление весов
W2 = W2 + learning_rate * np.outer(out_h, delta_o)  # Обновляем веса W2
W1 = W1 + learning_rate * np.outer(X, delta_h)      # Обновляем веса W1

# Вывод результатов
print("Выход сети:", out_o)
print("Ошибка:", error)
print("Обновленная матрица весов W1:\n", W1)
print("Обновленная матрица весов W2:\n", W2)



Выход сети: [0.50546733 0.46248164 0.51932954]
Ошибка: [-0.20546733  0.03751836  0.28067046]
Обновленная матрица весов W1:
 [[ 0.23060109 -0.14100624  0.00172322]
 [ 0.12915298  0.28902436  0.0054171 ]]
Обновленная матрица весов W2:
 [[-0.01739202  0.01055501 -0.00091722]
 [ 0.05333736 -0.19886871  0.01124331]
 [-0.0057421  -0.12641946  0.17069365]]
